### ISSUE TITLE
Image yang dikitim menggunakan sendSlide

### ISSUE THREAD

**Issue by aethelyn** [clicknetcafe/azamibot-md-multi#11]
Media yang dikirim menggunakan sendSlide tidak masuk ke directory yang seharusnya, dan hanya masuk ke /WhatsApp, jadi jika chat yg ada disitu mengaktifkan Dissapearing Message maka akan muncul file .nomedia yg mengakibatkan seluruh folder tidak terdeteksi lagi

**Comment by clicknetcafe** [comment]
> Media yang dikirim menggunakan sendSlide tidak masuk ke directory yang seharusnya, dan hanya masuk ke /WhatsApp, jadi jika chat yg ada disitu mengaktifkan Dissapearing Message maka akan muncul file .nomedia yg mengakibatkan seluruh folder tidak terdeteksi lagi

iya default dari WA nya
