### ISSUE TITLE
Baileys Warning

### ISSUE THREAD

**Issue by AnonGhostID** [clicknetcafe/azamibot-md-multi#15]
cara ngilangin baileys warning ini gimana yak?

```
[14:08:32.409] INFO (38): received phash in ack, resending message...
    class: "baileys"
    attrs: {
      "from": "xxxxxx@g.us",
      "class": "message",
      "id": "3EB04C3FCCA9EF3BCC86EE",
      "phash": "2:KC4daZuT",
      "count": "2",
      "t": "1734358112"
    }
[14:08:32.409] WARN (38): could not send message again, as it was not found
    class: "baileys"
    attrs: {
      "from": "xxxxx@g.us",
      "class": "message",
      "id": "3EB04C3FCCA9EF3BCC86EE",
      "phash": "2:KC4daZuT",
      "count": "2",
      "t": "1734358112"
    }
```
    
 muncul gini mulu bang

**Comment by AnonGhostID** [comment]
nvm bang dah nemu caranya.

**Comment by anderpru** [comment]
> muncul gini mulu bang

Did you solve it?
I'm still getting this message when I try to send a message in a group.

**Comment by AnonGhostID** [comment]
> > muncul gini mulu bang
> 
> Did you solve it? I'm still getting this message when I try to send a message in a group.

it has something to do with baileys logging. as you can see, the logging level in there is "warn". i'm solving it by changing the logging level into higher level. 

you can change the warn level into higher level such as error etc. in `lib/connection.js`

by changing the level higher than "warn" you may not seeing "updated plugins" info in logs.

```
const logger = P({
	timestamp: () => `,"time":"${new Date().toJSON()}"`,
	level: 'error', 
	transport: {
		target: 'pino-pretty',
		options: {
			colorize: true
		}
	}
}).child({ class: 'baileys' })
```
