### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Uunkn0wnN** [clicknetcafe/azamibot-md-multi#3]
npm i & yarn install error di replit
![Screenshot_20230828-103815](https://github.com/clicknetcafe/azamibot-md-multi/assets/95006878/5a77510c-8e56-4747-b785-4d1efa78693c)

**Comment by kangunduh** [comment]
> npm i & yarn install error di replit ![Screenshot_20230828-103815](https://user-images.githubusercontent.com/95006878/263607040-5a77510c-8e56-4747-b785-4d1efa78693c.jpg)

itu modul xfarr yg km install mngkin emg g support, aku run npm i aman2 aja sih
![Screenshot (148)](https://github.com/clicknetcafe/azamibot-md-multi/assets/143421060/980a5bb3-d86a-47f4-8251-e2b0f7bc7ade)
